### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by dovlamingoX1** [JunweiZheng93/MATERobot#2]
Hi

Do you have any link for the pretrained model(s) to run the inference using them? I wanted to test some images with material segmentation before running any training. 

Best
Don

**Comment by JunweiZheng93** [comment]
Hi Don,

I have uploaded the checkpoint for material segmentation. Check README for details. Close.

Best
Junwei

**Comment by dovlamingoX1** [comment]
Hi Junwei, 

sorry for writing in the issue again, I already tested running the script `inference_demo.py` with providing the path to the target image (`img_path`) and the `checkpoint_path = path/to/vit_tiny_p16_384.pth`. The script reported the error:   

Traceback (most recent call last):
  File "inference_demo.py", line 17, in <module>
    model = init_model(config_path, checkpoint_path, device='cuda:0')
  File "/home/Don/Desktop/models/MATERobot/materobot/apis/inference.py", line 55, in init_model
    dataset_meta = checkpoint['meta'].get('dataset_meta', None)
KeyError: 'meta'


Best
Don

**Comment by dovlamingoX1** [comment]
Hi Junwei, 

thank you very much! I tested the model, I have these results: 
Orginal: 
![1_ori](https://user-images.githubusercontent.com/126277919/226588983-8efa59f1-0324-4703-baf8-e508c1dfa0f1.png)
DMS:
![1_dms](https://user-images.githubusercontent.com/126277919/226589055-fbcdc1e8-262b-4a85-b75c-b04c1621f79a.png)
COCO:
![1_coco](https://user-images.githubusercontent.com/126277919/226589127-89e9975c-4d9c-4d8c-9917-50675044ab06.png)

Did I miss anything? or is the quality of the picture not that good for the segmentation?

Best,
Don

**Comment by JunweiZheng93** [comment]
Dear Don,

Sorry for my late reply. The checkpoint I uploaded so far is only for a single task (DMS material segmentation). Please pay attention to the difference between pretrained model and checkpoint in this repository. The former is the pretrained backbone for training, while the latter is the one you should use for inference.

Could you please share the inference code you used so that I can have a closer look? You need to uncomment the corresponding codes when using the single-task checkpoint.

Best
Junwei

**Comment by dovlamingoX1** [comment]
Dear Junwei, 

thank you for your answer, I am using your script `inference_demo.py`. You are right, I was using multi_task instead of single task. I already tested single task today and I have an error from `inference.py`. 
Code:  
![Screenshot from 2023-03-27 11-16-45](https://user-images.githubusercontent.com/126277919/227898573-098a1168-e96a-4053-8118-9625ff1d398d.png)

Running the script with these settings, I have the error: 

Traceback (most recent call last):
  File "inference_demo.py", line 22, in <module>
    result = inference_moe_model(model, img_path)
  File "/home/Don/Desktop/models/MATERobot/materobot/apis/inference.py", line 147, in inference_moe_model
    return results if is_batch else results[0][0], results[1][0]
TypeError: 'SegDataSample' object is not subscriptable



Best
Don

**Comment by JunweiZheng93** [comment]
Hi Don,

Please uncomment Line 21 and comment Line 22
Please  uncomment Line 24,25 and comment Line 26-29
Please uncomment Line 34

Best,
Junwei

**Comment by JunweiZheng93** [comment]
Hi Don,

Yes. They should match each other. However, we ignored the background category like the DMS paper, which means the material not included in the table will be assigned to an arbitrary category.

Best,
Junwei

**Comment by dovlamingoX1** [comment]
OK thx, I will close the issue. 
Best
Don
